name: anusha-firstproject/anusha414.Azure-pipeline
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Setup Java 8
      uses: actions/setup-java@v4.0.0
      with:
        distribution: zulu
        java-version: '8'
    - name: Run maven
      run: mvn --file pom.xml package
      env:
        MAVEN_OPTS: "-Xmx3072m"
    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v2.12.0
      if: always()
      with:
        junit_files: "**/surefire-reports/TEST-*.xml"
