name: first practice workflow
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs_on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - name: task1
       run: echo "hello world"
     - name: task2
       run: echo "this is my first job"
