name: workflow1
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: task1
        run: echo "Hello, world!"
  job2:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: task2
      run: echo "this is task2"
