name: first practice workflow
on:
  push:
    branches: ["master"]
  workflow_dispatch:
jobs:
  job1:
     runs_on: ubuntu-latest
     steps:
     - name: checkout task
       uses: actions/checkout@v3
     - name: task1
       run: echo "hello world"
     - name: task2
       run: echo "this is my first job"
